---
abstract: 'Read and write (Acrobat) FDF files.'
author:
  - unknown
build_requires:
  File::Copy: '0'
  Test::Deep: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PDF-FDF-Simple
provides:
  PDF::FDF::Simple:
    file: lib/PDF/FDF/Simple.pm
    version: '0.22'
  PDF::FDF::Simple::Builder:
    file: lib/PDF/FDF/Simple/Builder.pm
  PDF::FDF::Simple::Grammar:
    file: lib/PDF/FDF/Simple/Grammar.pm
  Parse::RecDescent::PDF::FDF::Simple::Grammar:
    file: lib/PDF/FDF/Simple/Grammar.pm
requires:
  Class::Accessor::Fast: '0'
  Compress::Zlib: '0'
  File::ShareDir: '0'
  Parse::RecDescent: '1.94'
  perl: v5.6.1
resources:
  repository: git://github.com/renormalist/pdf-fdf-simple.git
version: '0.22'
